# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sorting and Searching
author: Tomek Czajka
email: tczajka@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A blog about interesting algorithms and data structures.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sortingsearching.com" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  tczajka
facebook_username: tomek.czajka.one
google_analytics: UA-166046058-1
disqus:
  shortname: sortingsearching

# Build settings
markdown: kramdown
kramdown:
  math_engine: katex
future: true
theme: minima
plugins:
 - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - local.sh
  - production.sh
  - publish.sh

header_pages:
  - about.md

# Defaults.
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Tomek Czajka"
